include_recipe 'visualstudio::install_vs90'
include_recipe 'visualstudio::install_vs90sp1'
include_recipe 'visualstudio::install_vs100'
include_recipe 'visualstudio::install_vs100sp1'
include_recipe 'visualstudio::install_tfpt'